##################################################################################################
# OdbDesignServer deployment
##################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odbdesign-server-v1
  labels:
    app: odbdesign-server
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odbdesign-server
      version: v1
  template:
    metadata:
      labels:
        app: odbdesign-server
        version: v1
    spec:
      containers:
      - name: odbdesign-server
        image: ghcr.io/nam20485/odbdesign:nam20485-latest        
        imagePullPolicy: Always
        ports:
          - containerPort: 8888
            name: ods-dep-port
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "2"
            memory: 2Gi        
