apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: odbdesign-server-ingress
spec:
  rules:
   - http:
      paths:              
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: odbdesign-server
            port: 
              name: ods-svc-port
