remote_theme: pages-themes/dinky
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: OdbDesign
description: REST API and C++ library for parsing ODB++ Design archives 