# Dependency Review Action
#
# This Action will scan dependency manifest files that change as part of a Pull Request,
# surfacing known-vulnerable versions of the packages declared or updated in the PR.
# Once installed, if the workflow run is marked as required,
# PRs introducing known-vulnerable packages will be blocked from merging.
#
# Source repository: https://github.com/actions/dependency-review-action
name: 'Dependency Review'
on: 
  pull_request:
    branches: [ "main", "release", "development", "nam20485" ]

permissions:
  contents: read  

jobs:

  dependency-submission:
    runs-on: ubuntu-22.04
    permissions: 
      id-token: write
      contents: write
          
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Component detection 
        uses: advanced-security/component-detection-dependency-submission-action@v0.0.2       

  dependency-review:
    runs-on: ubuntu-22.04
    permissions: 
      contents: write
      pull-requests: write
    
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@4901385134134e04cec5fbe5ddfe3b2c5bd5d976 # v4.0.0
        with:
          comment-summary-in-pr: true
